// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc07ovut8bYRzt2VL1cRwyv9fnaig03_A',
    appId: '1:762194828363:web:073d4a03ec66881a8d41ce',
    messagingSenderId: '762194828363',
    projectId: 'numberlogin-7ad7f',
    authDomain: 'numberlogin-7ad7f.firebaseapp.com',
    storageBucket: 'numberlogin-7ad7f.appspot.com',
    measurementId: 'G-B3KQHLVYL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEiZwQJrbHZOiqTXJh5-xEDJJDakLB9EY',
    appId: '1:762194828363:android:e8fcafcc22090eb68d41ce',
    messagingSenderId: '762194828363',
    projectId: 'numberlogin-7ad7f',
    storageBucket: 'numberlogin-7ad7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXtfnE_WM4MXySXaL_b3JV42n-bSU_xXk',
    appId: '1:762194828363:ios:3192d5658507259f8d41ce',
    messagingSenderId: '762194828363',
    projectId: 'numberlogin-7ad7f',
    storageBucket: 'numberlogin-7ad7f.appspot.com',
    iosBundleId: 'com.example.numberAuthTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXtfnE_WM4MXySXaL_b3JV42n-bSU_xXk',
    appId: '1:762194828363:ios:7cd898d1679847048d41ce',
    messagingSenderId: '762194828363',
    projectId: 'numberlogin-7ad7f',
    storageBucket: 'numberlogin-7ad7f.appspot.com',
    iosBundleId: 'com.example.numberAuthTask.RunnerTests',
  );
}
